version: '2'
services:
  web:
    build: .
    container_name: ubuntu-apache
    volumes:
      - ./src:/app
      - ./logs/:/var/log/apache2
      - ./apache2:/etc/apache2
      - ./php:/etc/php
    ports:
      - "9000:80"
    links:
      - mariadb
  mariadb:
    image: mariadb
    container_name: mariadb-server
    volumes: 
      - ./dbdata:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: magento2
    ports:
      - 33060:3306
