<link href="<?php echo $this->getAssetUrl('SMTraining_Slider::css/style.css'); ?>" type="text/css" rel="stylesheet" />

<h1>SMTraining Slider</h1>
<div id="sm-slider-<?php echo $this->getData('slider_id'); ?>" class="sm-slider">
    <ul class="slider">
        <?php foreach ($this->getSlides() as $slide): ?>
            <li class="sm-item">
                <img src="<?php echo $this->getFullImagePath($slide->getImage()); ?>" alt="<?php echo $slide->getName(); ?>"/>
            </li>
        <?php endforeach; ?>
    </ul>
    <ul class="slider-control">
        <li><a href="javascript:void(0)" class="ctr-prev-slide">Prev</a></li>
        <li><a href="javascript:void(0)" class="ctr-next-slide">Next</a></li>
    </ul>
</div>

<!--<script src="--><?php //echo $block->getAssetUrl('SMTraining_Slider::js/script.js'); ?><!--"></script>-->
<script type="text/javascript">
//    require(['SMTraining_Slider/js/script']);
//    require(['sm_slider_script']);
    sm_slider("sm-slider-<?php echo $this->getData('slider_id'); ?>");
</script>